---
title: "Map"
author: "Caroline Sutton Chubb"
date: "2024-02-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data and Packages
```{r Packages, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(ggthemes)
library(scales)
library(ggmap)
library(viridis)
library(viridisLite)
library(ggrepel)    # For non-overlapping labels
```

```{r dataset, message=FALSE, warning=FALSE}
Data <- read.csv("Coded_Data.csv", na = c("", "NA", "N/A"))

Inclusions <-  Data %>% 
  filter(Include == "Y")
```

```{r prepare-data}
Inclusions <- Inclusions %>%
   group_by(Condensed_Outcomes, Condensed_Discipline, level, Study_Design) %>% 
   summarize(total = n()) %>% 
   mutate(proportion = total / sum(total))

table(Inclusions$level)
```

```{r EGM-1, warning=FALSE, echo=FALSE, fig.width=8, fig.height=(8/ 1.618)}
#Graph
set.seed(3)

EGM_Map <- ggplot(Inclusions, aes(x = Condensed_Discipline , y = Condensed_Outcomes, size = total, color = level)) +
  geom_point(alpha=0.5, position=position_jitter(h=0.2,w=0.25)) +
  scale_size(range = c(5, 10), name="Number of Studies") +
  geom_text_repel(aes(label = total, color = level),
                  force = .5, force_pull= 2, size =2.5, segment.colour = NA, box.padding = .5) +
  scale_fill_viridis(option = "H", breaks = c(0, 200, 400, 600)) +
  labs(title = NULL, x = "Discipline Categories", y = "Outcomes")  +
    theme_classic() + 
    theme(legend.title=element_blank(), legend.position = "right", plot.subtitle = element_text(size = 10, face = "italic"),
    plot.title = element_text(size = 16, face = "bold"), legend.text = element_text(size = 5)) +
  guides(size = FALSE)

#Preview
EGM_Map

#Save graph
ggsave(EGM_Map , filename = "EGM_Map.png", width = 8, height = 4.9, bg = "white")
ggsave(EGM_Map , filename = "EGM_Map.pdf", width = 8, height = 4.9, bg = "white")

```

```{r prepare-data}
Inclusions_2 <- Inclusions %>%
   group_by(Condensed_Outcomes, Condensed_Discipline, Study_Design)%>%
   summarize(total = n()) %>% 
   mutate(proportion = total / sum(total))

table(Inclusions_2$Study_Design)
```

```{r EGM-2, warning=FALSE, echo=FALSE, fig.width=8, fig.height=(8/ 1.618)}
#Graph
set.seed(3333)

EGM_Map_Design <- ggplot(Inclusions_2, aes(x = Condensed_Discipline , y = Condensed_Outcomes, size = total, color = Study_Design)) +
  geom_point(alpha=0.5, position=position_jitter(h=0.2,w=0.25)) +
  geom_text_repel(aes(label = total, color = Study_Design),
                  force = .5, force_pull= 2, size =2.5, segment.colour = NA, box.padding = .5) +
  scale_colour_brewer(palette="Set2") +
  scale_size(range = c(5, 10), name="Number of Studies") +
  labs(title = NULL, x = "Discipline Categories", y = "Outcomes")  +
    theme_classic() + 
    theme(legend.title=element_blank(), legend.position = "right", plot.subtitle = element_text(size = 10, face = "italic"),
    plot.title = element_text(size = 16, face = "bold"), legend.text = element_text(size = 5)) +
  guides(size = FALSE)

#Preview
EGM_Map_Design

#Save graph
ggsave(EGM_Map_Design , filename = "EGM_Map2.png", width = 8, height = 4.9, bg = "white")
ggsave(EGM_Map_Design , filename = "EGM_Map2.pdf", width = 8, height = 4.9, bg = "white")

```



